
package act1ej1;
import java.awt.Color;
import javax.swing.UIManager;

public class VentanaColores extends javax.swing.JDialog {

        public VentanaColores() {
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        
    } catch(Exception e){}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorPanel = new javax.swing.JPanel();
        ResetButton = new javax.swing.JButton();
        BlueButton = new javax.swing.JButton();
        GreenButton = new javax.swing.JButton();
        RedButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        ColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ColorPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ColorPanelMouseDragged(evt);
            }
        });
        ColorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ColorPanelMousePressed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        BlueButton.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        BlueButton.setText("Blue");
        BlueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueButtonActionPerformed(evt);
            }
        });

        GreenButton.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        GreenButton.setText("Green");
        GreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenButtonActionPerformed(evt);
            }
        });

        RedButton.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        RedButton.setText("Red");
        RedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ColorPanelLayout = new javax.swing.GroupLayout(ColorPanel);
        ColorPanel.setLayout(ColorPanelLayout);
        ColorPanelLayout.setHorizontalGroup(
            ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColorPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ColorPanelLayout.createSequentialGroup()
                        .addComponent(RedButton)
                        .addGap(27, 27, 27)
                        .addComponent(GreenButton)
                        .addGap(27, 27, 27)
                        .addComponent(BlueButton)
                        .addGap(18, 18, 18)
                        .addComponent(ResetButton))
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        ColorPanelLayout.setVerticalGroup(
            ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ColorPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RedButton)
                    .addComponent(GreenButton)
                    .addComponent(BlueButton)
                    .addComponent(ResetButton))
                .addGap(18, 18, 18)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Recuperar color original del panel
    Color color = UIManager.getColor ( "Panel.background" );
    
    //BOTONES
    private void RedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedButtonActionPerformed

       ColorPanel.setBackground(Color.red);
    }//GEN-LAST:event_RedButtonActionPerformed

    private void GreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenButtonActionPerformed
        // TODO add your handling code here:
        ColorPanel.setBackground(Color.green);
    }//GEN-LAST:event_GreenButtonActionPerformed

    private void BlueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueButtonActionPerformed
        // TODO add your handling code here:
        ColorPanel.setBackground(Color.blue);
    }//GEN-LAST:event_BlueButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        ColorPanel.setBackground(color);
    }//GEN-LAST:event_ResetButtonActionPerformed

    //mover rata
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private int xMouse, yMouse;
    private void ColorPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorPanelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        System.out.println("X: " + xMouse);
        System.out.println("Y: " + yMouse);
    }//GEN-LAST:event_ColorPanelMousePressed

    private void ColorPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorPanelMouseDragged
        // TODO add your handling code here:
        this.setLocation(
                this.getLocation().x + evt.getX() - xMouse, this.getLocation().y + evt.getY() - yMouse
        );
    }//GEN-LAST:event_ColorPanelMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlueButton;
    private javax.swing.JPanel ColorPanel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton GreenButton;
    private javax.swing.JButton RedButton;
    private javax.swing.JButton ResetButton;
    // End of variables declaration//GEN-END:variables
}
